CREATE TABLE IF NOT EXISTS videos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    youtube_id TEXT NOT NULL UNIQUE,
    title_original TEXT NOT NULL,
    description_original TEXT DEFAULT '',
    published_at TEXT,
    channel_id TEXT,
    channel_title TEXT,
    playlist_id TEXT,
    thumbnail_url TEXT,
    tags_json TEXT DEFAULT '[]',
    duration_iso TEXT,
    speaker_score INTEGER DEFAULT 0,
    speaker_status TEXT NOT NULL DEFAULT 'REVIEW',
    language TEXT DEFAULT '',
    subject TEXT DEFAULT '',
    content_type TEXT DEFAULT '',
    series TEXT DEFAULT '',
    lesson_number INTEGER,
    title_ar TEXT DEFAULT '',
    is_published INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
